##
# Build Stage
#
FROM ubuntu:focal as build

ENV KEYSTORE_PW="kspass"
ENV TRUSTSTORE_PW="tspass"

##
# Prerequesites
#
RUN sed -i 's|http://archive.ubuntu.com|http://azure.archive.ubuntu.com|g; s|http://security.ubuntu.com|http://azure.archive.ubuntu.com|g' \
        /etc/apt/sources.list /etc/apt/sources.list.d/*.list 2>/dev/null || true \
    && apt-get -o Acquire::Retries=5 -o Acquire::http::Timeout=60 \
        --allow-releaseinfo-change -y update \
    && apt-get -o Acquire::Retries=5 -o Acquire::http::Timeout=60 \
        -y upgrade \
    && DEBIAN_FRONTEND=noninteractive apt-get \
        -o Acquire::Retries=5 -o Acquire::http::Timeout=60 \
        -y --no-install-recommends install \
        openssl net-tools default-jdk maven \
        apache2-utils git apt-transport-https \
        ca-certificates curl gnupg lsb-release software-properties-common \
    && apt-get clean

##
# Certificates
#

# Self-signed Certs
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt \ 
    -subj "/C=US/ST=WA/L=Seattle/O=DIGI-UW/OU=DIGI/CN=localhost" \
    -addext "subjectAltName=DNS:*.openelis.org"

RUN mkdir /etc/openelis-global/
# Keystore
RUN openssl pkcs12 -inkey /etc/ssl/private/apache-selfsigned.key -in /etc/ssl/certs/apache-selfsigned.crt -export -out /etc/openelis-global/keystore --passin pass:${KEYSTORE_PW} --passout pass:${KEYSTORE_PW}
# # Client-facing Keystore
RUN cp /etc/openelis-global/keystore /etc/openelis-global/client_facing_keystore
# # Truststore
RUN keytool -import -alias oeCert -file /etc/ssl/certs/apache-selfsigned.crt -storetype pkcs12 -keystore /etc/openelis-global/truststore -storepass ${TRUSTSTORE_PW} -noprompt

RUN chmod -R a+rwx /etc/openelis-global/
